# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20180827_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='time_created',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='time_updated',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='cart',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=5, default=0.085, max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=50),
        ),
    ]
