# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20180828_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='timestamp',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='updated',
            new_name='time_updated',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tax_total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
