# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20180828_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='line_item_total',
            new_name='line_total',
        ),
    ]
