# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-24 02:03
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180809_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', null=None, to='products.Tag'),
        ),
    ]
