# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-24 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
