# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='address',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='university',
            field=models.CharField(choices=[('utp', 'Universiti Teknologi Petronas')], default='utp', max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.UserAddress'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.UserCheckout'),
        ),
    ]
