# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-30 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180830_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.UserAddress', unique=True),
        ),
    ]
