# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-12 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180912_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='apartment',
            field=models.CharField(blank=True, choices=[('a1', '1'), ('a2', '2'), ('a3', '3'), ('a4', '4')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='block',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G'), ('h', 'H'), ('i', 'I'), ('j', 'J'), ('k', 'K')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='level',
            field=models.CharField(blank=True, choices=[('l1', 'Level 1'), ('l2', 'Level 2'), ('l3', 'Level 3'), ('l4', 'Level 4'), ('l5', 'Level 5')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='room',
            field=models.CharField(blank=True, choices=[('r1', '1'), ('r2', '2'), ('r3', '3'), ('r4', '4'), ('r5', '5'), ('r6', '6')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='village',
            field=models.CharField(blank=True, choices=[('v1', 'Village 1'), ('v2', 'Village 2'), ('v3', 'Village 3'), ('v4', 'Village 4'), ('v5', 'Village 5'), ('v6', 'Village 6'), ('sibc', 'SIBC')], max_length=60, null=True),
        ),
    ]
