# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-24 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_time_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
