# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-12 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180912_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='block',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='level',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='room',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='university',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='village',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
